//! FFI bindings to [libmongocrypt](https://github.com/mongodb/libmongocrypt).
//!
//! These bindings are generated by [rust-bindgen](https://github.com/rust-lang/rust-bindgen).

#[allow(nonstandard_style)]
mod bindings;
#[cfg(test)]
mod test;

pub use bindings::*;
